AllCops:
  TargetRubyVersion: 2.7
  
Metrics/MethodLength:
        Enabled: false

Metrics/AbcSize:
        Enabled: false

Style/BlockDelimiters:
        Enabled: false

Style/MultilineBlockChain:
        Enabled: false

Layout/SpaceBeforeBlockBraces:
        Enabled: false

Layout/SpaceInsideBlockBraces:
        Enabled: false

Layout/LeadingCommentSpace:
        Enabled: false

Metrics/LineLength:
        Max: 9000
