#!/usr/bin/env bash
BASE=$(cd "$(dirname "${0}")" && pwd)

curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > dein_installer.sh
sh ./dein_installer.sh ~/.cache/dein

[[ -L ~/.rubocop.yml ]] || ln -s ${BASE}/.rubocop.yml ~/

nvim --headless -c "try|call dein#update()|UpdateRemotePlugins|finally|qall!|endtry<cr>"
