#!/usr/bin/env bash
BASE=$(cd "$(dirname "${0}")" && pwd)

[[ -L ~/.rubocop.yml ]] || ln -s ${BASE}/.rubocop.yml ~/

git submodule update --init --recursive

vim --headless -c "try | call dein#update() | UpdateRemotePlugins | finally | qall! | endtry"
