#!/usr/bin/env bash
BASE=$(cd "$(dirname "${0}")" && pwd)

[[ -L ~/.rubocop.yml ]] || ln -s ${BASE}/.rubocop.yml ~/

git submodule foreach 'git checkout $(git config -f ../.gitmodules --get submodule.$path.branch)'
git submodule foreach git pull

vim --headless -c "try | call dein#update() | UpdateRemotePlugins | finally | qall! | endtry"
